In [2]:
import tensorflow as tf
import numpy as np

from keras import backend as K

Using TensorFlow backend.


## tf.sum

In [3]:
K

<module 'keras.backend' from 'D:\\Miniconda3\\lib\\site-packages\\keras\\backend\\__init__.py'>

In [4]:
tf

<module 'tensorflow' from 'D:\\Miniconda3\\lib\\site-packages\\tensorflow\\__init__.py'>

In [5]:
sess = tf.Session()

In [6]:
a = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
b = np.array([[1, 1, 1, 1], [2, 2, 2, 2]])

s = K.sum(a, axis=1)

with sess.as_default():
    print(s.eval())

[10 10]


In [7]:
b - a

array([[ 0, -1, -2, -3],
       [-2, -1,  0,  1]])

In [9]:
s = K.sum(tf.square(b - a), axis=1)

with sess.as_default():
    print(s.eval())

[14  6]


## tf.random_normal

In [25]:
?K.random_normal

In [10]:
def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(
        shape=(batch_size, latent_dim), 
        mean=0.,
        stddev=epsilon_std)
    return z_mean + K.exp(z_log_var / 2) * epsilon

In [36]:
random_normal_test = tf.random_normal(shape=(10, 3), mean=10.0, stddev=20.0, seed=2019)

In [37]:
with sess.as_default():
    normal_random_result = random_normal_test.eval()
    print(normal_random_result)

[[  9.37329     -6.326332    22.968203  ]
 [ 26.539455     2.4116778   -1.6199818 ]
 [ -2.1089182   12.655096    -8.273937  ]
 [  0.99575424 -12.2054825   28.540304  ]
 [  0.8335781   54.42662     -0.06710243]
 [ 16.96736     47.359287    35.854206  ]
 [ -8.770863    42.750458    16.931347  ]
 [ 55.83802     30.724516    30.408133  ]
 [-20.826736     6.97353     -7.865055  ]
 [ 12.258916    16.040808    40.617813  ]]


In [38]:
np.mean(normal_random_result, axis=0)

array([ 9.109986 , 19.481016 , 15.7493925], dtype=float32)

In [39]:
np.std(normal_random_result , axis=0)

array([20.087694, 22.005812, 17.723587], dtype=float32)

In [42]:
np.mean(normal_random_result, axis=1)

array([ 8.67172   ,  9.110384  ,  0.75741357,  5.776859  , 18.3977    ,
       33.393616  , 16.970314  , 38.990223  , -7.2394204 , 22.972513  ],
      dtype=float32)

In [43]:
np.std(normal_random_result , axis=1)

array([11.969728 , 12.433637 ,  8.781343 , 16.97447  , 25.478949 ,
       12.5288515, 21.033508 , 11.913892 , 11.358029 , 12.572275 ],
      dtype=float32)