In [23]:
# coding:utf8

import pandas as pd
import numpy as np
import sys
import os
from sklearn.metrics import classification_report
import itertools
from sklearn.externals import joblib
import sklearn

In [6]:
model_file_path='./fp_model@xgboost.standardize_pair.m'

In [8]:
cur_model = joblib.load(model_file_path)

C:\Program Files\Anaconda3\lib\site-packages\sklearn\base.py:311: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Program Files\Anaconda3\lib\site-packages\sklearn\base.py:311: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [9]:
cur_model

GridSearchCV(cv=3, error_score='raise',
       estimator=XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=nan, n_estimators=150, nthread=4,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=2017, silent=True, subsample=1),
       fit_params=None, iid=False, n_jobs=12,
       param_grid={'gamma': [0.1, 0.3], 'colsample_bytree': [0.6, 0.9], 'subsample': [0.6, 0.9], 'min_child_weight': [1, 3], 'max_depth': [4, 6], 'n_estimators': [100, 300], 'learning_rate': [0.1], 'reg_alpha': [0.1, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='roc_auc', verbose=0)

In [26]:
cur_model.best_params_

{'colsample_bytree': 0.9,
 'gamma': 0.3,
 'learning_rate': 0.1,
 'max_depth': 6,
 'min_child_weight': 1,
 'n_estimators': 300,
 'reg_alpha': 0.1,
 'subsample': 0.9}

In [68]:
import numpy as np
import xgboost as xgb
import pandas as pd

In [70]:
X = np.arange(11*20).reshape((20, 11))
X.shape
train_x = X.astype(float) 
type(X)

df_x = pd.DataFrame(train_x)

In [72]:
df_x.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
dtype: object

In [73]:
df_x.head(1)

0    1    2    3    4    5    6    7    8    9     10
0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0

In [77]:
type(train_x)

numpy.ndarray

In [79]:
y = np.array([0]*20)
y 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
dtrain = xgb.DMatrix(df_x.values, label=y)
dtrain.get_label()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [98]:
param={
    'max_depth':2,
    'eta':1,
    'objective': 'binary:logistic'
}

In [100]:
bst = xgb.train(param, dtrain)

In [109]:
bst.predict(x)

array([0.04090196, 0.04090196, 0.04090196, 0.04090196, 0.04090196,
       0.04090196, 0.04090196, 0.04090196, 0.04090196, 0.04090196,
       0.04090196, 0.04090196, 0.04090196, 0.04090196, 0.04090196,
       0.04090196, 0.04090196, 0.04090196, 0.04090196, 0.04090196],
      dtype=float32)

In [122]:
cur_model.best_estimator_.predict(df_x)

TypeError: 'str' object is not callable

In [24]:
type(cur_model) == sklearn.model_selection._search.GridSearchCV

True

In [21]:
cur_model

GridSearchCV(cv=3, error_score='raise',
       estimator=XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=nan, n_estimators=150, nthread=4,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=2017, silent=True, subsample=1),
       fit_params=None, iid=False, n_jobs=12,
       param_grid={'gamma': [0.1, 0.3], 'colsample_bytree': [0.6, 0.9], 'subsample': [0.6, 0.9], 'min_child_weight': [1, 3], 'max_depth': [4, 6], 'n_estimators': [100, 300], 'learning_rate': [0.1], 'reg_alpha': [0.1, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='roc_auc', verbose=0)